version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./nodejs:/app

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/code
      - /var/run/docker.sock:/var/run/docker.sock:ro

  python-executor:
    image: python:3.9
    entrypoint: ["python3", "-c"]
