version: "3"
services:
  web:
    image: siyoonlee/hello-docker-web
    volumes:
      - /app/node_modules
      - ./web:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: siyoonlee/hello-docker-nginx
    ports:
      - "80:80"

  nodejs:
    image: siyoonlee/hello-docker-nodejs
    volumes:
      - /app/node_modules
      - ./nodejs:/app
    mem_limit: 256m

  python:
    image: siyoonlee/hello-docker-python
    volumes:
      - ./python:/code
    mem_limit: 256m
