version: "3"
services:
  frontend:
    image: siyoonlee/hello-docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: siyoonlee/hello-docker-nginx
    ports:
      - "80:80"

  backend:
    image: siyoonlee/hello-docker-backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m
